ALTER TABLE offers ADD COLUMN IF NOT EXISTS diagnosis_cost NUMERIC(10,2);
ALTER TABLE offers ADD COLUMN IF NOT EXISTS labor_cost NUMERIC(10,2);
ALTER TABLE offers ADD COLUMN IF NOT EXISTS parts_cost NUMERIC(10,2);
ALTER TABLE offers ADD COLUMN IF NOT EXISTS transport_cost NUMERIC(10,2);
ALTER TABLE offers ADD COLUMN IF NOT EXISTS additional_cost NUMERIC(10,2);
ALTER TABLE offers ADD COLUMN IF NOT EXISTS repair_time_minutes INTEGER;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS price_explanation TEXT;
